### PR TITLE
changes needed for v0.13 janestreet packages

### PR DESCRIPTION
**Pull request by anuragsoni**

### CODE REVIEW

File: pgx.opam [hunk 1]
```diff
@@ -20,7 +20,7 @@ depends: [
   "sexplib0" {>= "v0.11.0"}
 
   "bisect_ppx" {build & >= "1.4.1"}
-  "dune" {build & >= "1.1.0"}
+  "dune" {>= "1.1.0" & < "2.0"}
```
Comment (brendanlong) [inline pgx.opam]: What's wrong with dune >= 2.0?

File: pgx/src/io_intf.ml [hunk 2]
```diff
@@ -5,7 +5,9 @@ module type S = sig
   val (>>=) : 'a t -> ('a -> 'b t) -> 'b t
   val catch : (unit -> 'a t) -> (exn -> 'a t) -> 'a t
   type in_channel
+  val sexp_of_in_channel : in_channel -> Sexplib0.Sexp.t
   type out_channel
+  val sexp_of_out_channel : out_channel -> Sexplib0.Sexp.t
```
Comment (brendanlong) [inline pgx/src/io_intf.ml]: Why do we need these to be sexp-able? Couldn't we just declare them as `sexp_opaque`?

File: pgx/src/io_intf.ml [hunk 3]
```diff
@@ -25,7 +27,8 @@ module type S = sig
   module Sequencer : sig
     type 'a monad = 'a t
     type 'a t
-
+    val sexp_of_t : 'a t -> Sexplib0.Sexp.t
+    val t_of_sexp : Sexplib0.Sexp.t -> 'a t
```
Comment (brendanlong) [inline pgx/src/io_intf.ml]: Same thing here. I'm pretty sure sexping a Sequencer doesn't make any sense?

File: pgx/src/pgx.ml [hunk 4]
```diff
@@ -453,14 +453,14 @@ module Make (Thread : IO) = struct
   open Thread
 
   type conn =
-    { ichan: in_channel sexp_opaque (* In_channel wrapping socket. *)
-    ; chan: out_channel sexp_opaque (* Out_channel wrapping socket. *)
```
Comment (brendanlong) [inline pgx/src/pgx.ml]: Oh I see. What's wrong with sexp_opaque?

File: pgx_async/bin/pgx_async_example.ml [hunk 5]
```diff
@@ -9,7 +9,7 @@ module Employee = struct
         id SERIAL PRIMARY KEY,
         name VARCHAR(100) NOT NULL UNIQUE);
     |}
-    |> Deferred.ignore
+    |> Deferred.ignore_m
```
Comment (brendanlong) [inline pgx_async/bin/pgx_async_example.ml]: What changed with `ignore`?

File: pgx_async/src/pgx_async.ml [hunk 6]
```diff
@@ -87,6 +90,12 @@ module Thread = struct
     type 'a monad = 'a t
     type 'a t = 'a Sequencer.t
 
+    let sexp_of_t _ = Sexplib0.Sexp.Atom "<opaque>"
+    let t_of_sexp sexp =
+      Sexplib0.Sexp_conv.of_sexp_error
+        "opaque_of_sexp: cannot convert opaque values"
+        sexp
```
Comment (brendanlong) [inline pgx_async/src/pgx_async.ml]: Can we just not provide `t_of_sexp`?

File: pgx.opam (hunk 1 above)
Comment (anuragsoni) [reply pgx.opam]: There was a problem with inline_tests on core versions 0.11. This won't be required if its fine to just depend on versions of core that use dune instead of jbuilder

File: pgx_async/bin/pgx_async_example.ml (hunk 5 above)
Comment (anuragsoni) [reply pgx_async/bin/pgx_async_example.ml]: It was just renamed to `ignore_m`

From their docs:
```
val ignore_m : 'a t -> unit t
ignore_m t is map t ~f:(fun _ -> ()). ignore_m used to be called ignore, but we decided that was a bad name, because it shadowed the widely used Caml.ignore. Some monads still do let ignore = ignore_m for historical reasons.
```

File: pgx_async/src/pgx_async.ml (hunk 6 above)
Comment (anuragsoni) [reply pgx_async/src/pgx_async.ml]: We should remove this i think. `sexp_of` might be the only converted we need since we can't convert it back from sexp anyways. I'll remove the `t_of_sexp` converters

File: pgx/src/io_intf.ml (hunk 3 above)
Comment (anuragsoni) [reply pgx/src/io_intf.ml]: Agreed. Most of this was a result of trying to fix compilation errors from whereever we were using `@@deriving sexp`. I'll change them all to use `sexp_of` and remove the `t_of_sexp` converters

File: pgx/src/pgx.ml (hunk 4 above)
Comment (anuragsoni) [reply pgx/src/pgx.ml]: `sexp_opaque` was moved to be `[@sexp.opaque]` in the newer versions of ppx_sexp_conv. 
I didn't think i had way to have this work with both 0.11 and 0.13 without writing handwritten converters for the opaque items

File: pgx_async/src/pgx_async.ml (hunk 6 above)
Comment (anuragsoni) [reply pgx_async/src/pgx_async.ml]: Removed the t_of_sexp

File: pgx/src/dune [hunk 7]
```diff
@@ -1,6 +1,17 @@
+(* -*- tuareg -*- *)
+
+let preprocess =
+  match Sys.getenv "BISECT_ENABLE" with
+  | "yes" -> "(preprocess (pps bisect_ppx ppx_jane))"
+  | _ -> "(preprocess (pps ppx_jane))"
+  | exception Not_found -> "(preprocess (pps ppx_jane))"
```
Comment (brendanlong) [inline pgx/src/dune]: What changed here?

Comment (anuragsoni) [reply pgx/src/dune]: This will allow publishing pgx to opam without needing to remove bisect_ppx from opam files or dune files. Bisect is a dev only dependency, but without this we'd be forced to mark it as a test dependency. This will avoid having any end-user needing to install bisect just to use pgx

Comment (anuragsoni) [reply pgx/src/dune]: i've moved this back to the dune file from `master`. We can decide on how to define bisect_ppx as a dependency at a later stage.

File: pgx/src/pgx.ml [hunk 8]
```diff
@@ -760,9 +760,14 @@ module Make (Thread : IO) = struct
 
   module Prepared = struct
     type s =
-      { conn : conn Sequencer.t sexp_opaque
+      { conn : conn Sequencer.t
```
Comment (brendanlong) [inline pgx/src/pgx.ml:763]: Could we use `[@sexp.opaque]` here like we do above?

File: pgx_async/test/dune [hunk 9]
```diff
@@ -1,15 +1,3 @@
-(executables
+(tests
```
Comment (brendanlong) [inline pgx_async/test/dune:1]: Does this require a particular version of dune (is dune >1.1 still accurate)?

Comment (anuragsoni) [reply pgx_async/test/dune:1]: dune 1.1 is still dune. The tests stanza has been there since version 1.0 i believe.
